### ISSUE TITLE
Water Movement

### ISSUE THREAD

**Issue by ghost** [Btan2/Q_Move#3]
Hey there! 

**Excelent project**! Very smooth movement.
How hard would it be to further extend this – to support **water**? 
Considering that it's just air movement but with low or no gravity.

I've tried to create a static body without any layer and giving it the "WATER" group. 
It's kind of working but you **can't swim up or down**, in the look direction.
And the player **doesn't fall** into body of water.

P. S. I'm rebuilding my game and this project would be great as a base! 
Any plans to continue the work on this project?

**Comment by Btan2** [comment]
Hello,

I've recently picked up this project again and coincidentally water movement is something I am planning to add next. The trick with water is figuring out when the player is submerged or above the surface, as well as finding mountable ledges so they can climb out.
I have also been attempting to smooth out a few edge cases and improving step detection. There are still a few annoyances that I am determined to get rid of. The step_move function will be a little more complex but more precise. The current iteration runs well on Godot 3.5 and I'd suggest keeping up to date with the latest version as I plan to slowly update the entire project so it runs on Godot 4. 
_An update with improved step detection should be here in about a week or so._

NB: To fly up/down you simply multiply move input vars by the camera's look direction i.e. the XYZ basis.
You'll need another move input var ("umove") so you can move vertically.

```
func fly_move():
  var head_dir = head.global_transform.basis
  var wishdir = (head_dir.x * smove + head_dir.y * umove + -head_dir.z * fmove).normalized()

  if wishdir != Vector3.ZERO:
      velocity = velocity.linear_interpolate(wishdir * movespeed, ACCELERATE * deltaTime) 
  else:
      velocity = velocity.linear_interpolate(Vector3.ZERO, MOVEFRICTION * deltaTime) 

  velocity = move_and_slide(velocity)
```
